### ISSUE TITLE
Cannot connect to Local instance of Augur UI using Ledger Nano S

### ISSUE THREAD

**Issue by Augurist** [AugurProject/augur-ui#1880]
The Augur UI does not connect to a Ledger Nano S while the Augur node is hosted locally. This feature does work when accessing the Ledger from https://dev.augur.net. Tested on Ubuntu 18.04 and Windows 10.

This message is displayed in the JavaScript console when the "Connect to Ledger" button is pressed, regardless of whether a ledger is plugged in:

```
u2f-api.js:544 Failed to execute 'postMessage' on 'DOMWindow': 
The target origin provided ('chrome-extension://kmendfapggjehodndflmmgagdbamhnfd') 
does not match the recipient window's origin ('null').
```
See notes: https://hackmd.io/eEKPQUljQoO3VseHRcMH7A#

**Comment by Augurist** [comment]
This does not seem to be a problem after I installed ssl certs and accessed augur through https://localhost.

**Comment by Augurist** [comment]
After installing a trusted SSL certificate for localhost (accessed through google-chromium), the ledger is recognized, but the ledger transaction prompts are non-existent or incorrect. When attempting to connect with the ledger, no prompt is shown, but scrolling through menus on the ledger will eventually trigger a login through the Augur UI. When attempting to sign transactions on the ledger, the prompt is slow to appear or never appears. The JavaScript console shows: Unknown error from Ledger. These errors do not seem to appear when accessing augur through https://dev.augur.net, but my understanding is that upon launch, end users will need to find their own host for Augur UI, and will likely use localhost.

**Comment by bthaile** [comment]
Post launch, users will be using augur-app which has a hosted augur-nod locally

**Comment by sharkcrayon** [comment]
@bthaile I'm assigning you to this issue since it relates closely to the work you're already doing with Ledger & SSL certs. Can you update @Augurist on your progress, if this is fixed, and steps to follow for him to retest if it is fixed?

**Comment by bthaile** [comment]
We have a ssl solution with the newest augur-app, should be fixed with `
1.0.0-alpha.14`

we have instruction on how to generate self signed certs for mac. We'll add instructions for other OSs as we finalize out approach.

Here are the instructions: 
https://github.com/AugurProject/augur-app

look for newest version of augur-app to come out soon

**Comment by sharkcrayon** [comment]
@Augurist Can you retest using the directions that bthaile supplied?

**Comment by bthaile** [comment]
augur-app now generates self signed certificate files. We added a button to do the generating (enable ssl) or remove the cert files (disable ssl).

Newest augur-app will work. 

We are having issues getting SSL enabled in FireFox. Chrome is the way to go for now.

**Comment by adrake33** [comment]
Closing this for now. Feel free to reopen if this is still an issue.
