### ISSUE TITLE
Market creation results in nothing

### ISSUE THREAD

**Issue by Keref** [AugurProject/augur-ui#1992]
While the transaction went through https://etherscan.io/tx/0x7881c47cf27b0eb2a4bd0d3f3bdf2a4ebccb8c87d8f40566e8fa3a3c6a2cc103
the question doesn't appear on the interface after 6h+.

Is there any way to know the state of a creation? At the moment both the REP tokens and the liquidity Eth are in limbo as well...

**Comment by maxenceC** [comment]
Same here, all the transacations went through, yet no market show up and the transactions disappeared from my account 30 mins after creations : 

Some of the transactions to create the market and buy the shares:

https://etherscan.io/tx/0xd9133fde5dee6aba3f7584803524a95e305d14f5859c33c6d84e8a7dbe0fa273

https://etherscan.io/tx/0x8165b6a3a879e994f0a95863b4ee5268b4612845eb25487878f1fbcce0c7d5cd

https://etherscan.io/tx/0x283b4f474446234b000cf287bc680242611a70cec7ab881d956c1661ec814f6e

https://etherscan.io/tx/0x1110b59e6c9dfe2817187a6c2252cfec6630c43cd8b3d6cee8848fa730307442

**Comment by maxenceC** [comment]
>We suggest using v1.0.2 of augur-app and when connected click the reset button

I am currently using v1.0.2, and encountered the problem with this version

Will the market transaction go through ? 
Or should I create it again ?

**Comment by bthaile** [comment]
We've not pushed a patch for the augur-node sync issue. We've only pushed a reset button to help meditate the issue. 

Based on the tx you posted, looks like your transactions went through. Seems the issue is your local augur-node (which is bundled in augur-app) needs to be reset.

**Comment by maxenceC** [comment]
>Based on the tx you posted, looks like your transactions went through. Seems the issue is your local augur-node (which is bundled in augur-app) needs to be reset.

Ok I'm giving this a try, will report back, thanks

**Comment by maxenceC** [comment]
@bthaile Sorry, But where is the reset button supposed to be ?

Can't find it

**Comment by bthaile** [comment]
![screen shot 2018-07-11 at 9 11 10 am](https://user-images.githubusercontent.com/3970376/42577658-6a348302-84ea-11e8-9144-67cee5b4ff0c.png)

big button at the bottom

**Comment by maxenceC** [comment]
@bthaile Ok, it's "invisible" on my macbook 2014 (app can't be un-zoomed), just so you know

**Comment by bthaile** [comment]
Yes, we are aware of multiple issue with different displays, our apologies. We pushed out before our design team had a chance to give devs direction.

**Comment by maxenceC** [comment]
@bthaile After reset and re-sync, not data show up on my account. No market, and not shares (They initially showed up after creation)

**Comment by maxenceC** [comment]
Ok, I'm trying again the same market creation, with the same parameters

**Comment by maxenceC** [comment]
Same test, same result : 

- I deleted V1.0.2,  reinstalled and click the reset button

- After sync, I created a new market, transactions went through, as well as buying initial liquidity : 

https://etherscan.io/tx/0x48099aeef69c686193bfea849e0335210d6dc7d5e8cec9c3f77a7a3c6ae0b6cb

https://etherscan.io/tx/0x1a1ee940b7aa12a7843ce12605acfa386276e712e64673938b759c2cb5e0e833

The creation showed up for a moment in the UI, and then everything disappeared from "My account". Here are some screenshots : 

https://imgur.com/a/S6RgMqq

Of course, the market isn't showing up in the market lists

I'm stopping for now, I can't throw more money down the well for the moment 😁

Hope this helps !

**Comment by maxenceC** [comment]
This quickfix worked: 

https://github.com/AugurProject/augur-app/issues/78

But the reset button didn't do anything (It's supposed to do the same thing, no ?)

**Comment by bthaile** [comment]
We’ll ne releasing a new version that clears the database and resets the config file. 
Not sure on ETA, there are some critial fixes being tested.

**Comment by Keref** [comment]
So what data is manually to be erased? I removed the leveldb folder, but my markets still don't appear.

**Comment by bthaile** [comment]
Database folder location. With the new 1.0.3 augur-app the database should be able to recover when block processing occurs. 

If you totall want to start fresh, you can delete the db files in this directory then start up the app. 

Windows: C:\\Users\\<User Name>\\AppData\\Roaming\\<application name>
MacOS: /Users/<User Name>/Library/Application Support/<application name>
linux: /home/<User Name>/.<application name>
