### ISSUE TITLE
Reporting fee is rendered incorrectly

### ISSUE THREAD

**Issue by burdakovd** [AugurProject/augur-ui#1997]
Normally it shows as 1%.

Case 1. During order creation it showed up as 100%.
Case 2. For market 0x3509e2ff3188a6ac8c377ec22457ef2e64e4be40 it shows as 0.01%

Also @achapman commented on this (no idea what it means): "confirmed the Universe currently has a fee divisor for reporting of 10000.".

Screenshots attached
![image](https://user-images.githubusercontent.com/5193161/42605731-8af0567a-8571-11e8-8ab4-e05eda934415.png)
![image](https://user-images.githubusercontent.com/5193161/42605758-a1ba6cec-8571-11e8-9fda-86ceeee627ba.png)

**Comment by bthaile** [comment]
https://app.clubhouse.io/augur/story/13826/market-creation-reporter-fee-showing-100

**Comment by sharkcrayon** [comment]
It shows as 100% during market creation as well:

![image](https://user-images.githubusercontent.com/4355755/42705742-3488f362-86cc-11e8-84a2-2df15a10a1c2.png)

**Comment by phoebemirman** [comment]
a fix for this has been merged
