### ISSUE TITLE
Ether returned if FILL ORDERS ONLY is checked

### ISSUE THREAD

**Issue by nojacko** [AugurProject/augur-ui#2005]
I'm not sure if this is a bug or just something confusing.

(Excuse the crapping annotations. Usually do this on a Mac but it's Windows today.)

![capture](https://user-images.githubusercontent.com/1667141/42669712-e2fd6596-864e-11e8-9fc0-96ad7c652bee.PNG)

1. Went to that market http://localhost:8080/#/market?description=croatia_v_england_result_after_90_minutes&id=0xc1d053b5c6053a9627eaa0b00974f3f04b4297da
1. Clicked England outcome.
1. Clicked the order I wanted to short.
1. Clicked Review and submitted transaction.

The transaction just returned my Ether. I was told on Discord "you checked [or inadvertently checked] the fill order only box".

Since I clicked the order and it checked that box, I thought it would be correct and the wording sounds like checking it would only fill orders and not create new ones.

My impression is that this is a UI bug (checking the box it shouldn't) AND/OR lack of details about what the checkbox actually does (couldn't see anything in the docs).

**Comment by nojacko** [comment]
I was using 1.0.3.

**Comment by bthaile** [comment]
Its possible that the order was already taken when your order was processed. 

Or there is a bug with phamton orders on the book that cant be taken. We have a fix in 1.0.5 so phamton orders are removed from the order book.

**Comment by nojacko** [comment]
That's probably the issue. Thanks.
