### ISSUE TITLE
Please auto-open "My Positions" in single market view

### ISSUE THREAD

**Issue by lhaste** [AugurProject/augur-ui#2021]
Viewing open orders here requires an extra click, when it really seems like they should just be displayed.  

<img width="1218" alt="screen shot 2018-07-17 at 8 30 39 am" src="https://user-images.githubusercontent.com/32305725/42827641-c3bef096-899b-11e8-8628-f436d52529da.png">

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/14665/github-please-auto-open-my-positions-in-single-market-view

**Comment by phoebemirman** [comment]
a change for this has been merged and will be in the next release.
