### ISSUE TITLE
Don't auto scroll down when clicking a single market from my-positions

### ISSUE THREAD

**Issue by lhaste** [AugurProject/augur-ui#2023]
Right now, when you click to a single market from `my-positions` it scrolls the page down (ostensibly so you can view your positions even though the positions are not visible/open).

Would be great if going back didn't require an extra scroll back up and the positions were visible (related to #2021).  

Note how the "back" link is obscured in the image.

<img width="1607" alt="screen shot 2018-07-17 at 8 36 33 am" src="https://user-images.githubusercontent.com/32305725/42828018-9a510720-899c-11e8-98f8-8b7957cd45ff.png">

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/14665/github-please-auto-open-my-positions-in-single-market-view

**Comment by phoebemirman** [comment]
a fix for this has been merged
