### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Sm00g15** [AugurProject/augur-ui#2034]
When creating a contract, I've found that it's a pain if I add extra bids on accident. Is there any way to remove bids when creating a market, or will I have to start the market creation process all over again?
![screen shot 2018-07-18 at 4 42 50 pm](https://user-images.githubusercontent.com/14209806/42860128-c979ec48-8aa9-11e8-9374-29856ac1fd6e.jpg)

**Comment by bthaile** [comment]
Dup of 
https://github.com/AugurProject/augur-app/issues/117

Closing
