### ISSUE TITLE
Be able to enter numETH and limitPrice and have numShares auto-calculated

### ISSUE THREAD

**Issue by lhaste** [AugurProject/augur-ui#2039]

**Comment by bthaile** [comment]
I think there is enough response in the trading form that users can get the ETH they want to spend by inputting price and quantity. 

Issue is users can trade using shares so the logic gets complex.

**Comment by bthaile** [comment]
I think there is enough response in the trading form that users can get the ETH they want to spend by inputting price and quantity. 

Issue is users can trade using shares so the logic gets complex.
