### ISSUE TITLE
Market Creation: cannot set valid tlds as resolution source

### ISSUE THREAD

**Issue by TristanH** [AugurProject/augur-ui#2061]
For example, the UI does not allow setting https://predictions.global as the resolution website, despite it being a valid url:

<img width="565" alt="screen shot 2018-07-21 at 2 35 01 pm" src="https://user-images.githubusercontent.com/1284332/43039077-84f03d92-8cf3-11e8-8644-6009a8378ab4.png">

**Comment by bthaile** [comment]
https://app.clubhouse.io/augur/story/13947/url-verification-doesn-t-take-long-extensions-in-to-account

totally agree, we are going to remove the url validation and allow for 128 characters in the field. I just put in a PR.
