### ISSUE TITLE
Non-null position in a resolved market (w/ gains already claimed)

### ISSUE THREAD

**Issue by jragosa** [AugurProject/augur-ui#2076]
![image](https://user-images.githubusercontent.com/34345327/43148570-de958e28-8f65-11e8-943c-3c8c51d391f3.png)

I have a non-null position displayed (Portfolio>Positions>Resolved) in a resolved market for which my gains were already claimed.

**Comment by bthaile** [comment]
Your saying you already claimed your winnings. Also your position says you now have 0 quantity shares? 

Are you thinking the position would go away?

**Comment by jragosa** [comment]
It did go away ater a few days. This issue can be closed.

**Comment by justinbarry** [comment]
Thank you for your response!
