### ISSUE TITLE
IPFS hosting workflow is broken.

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur-ui#2149]
```
docker container run -d --name ipfs-host -v /export -p 1234:8080 ipfs/go-ipfs:release
docker container run --rm -it --volumes-from ipfs-host micahzoltu/augur-ui-extractor augur-ui-5.4.0.tgz
docker container exec -it ipfs-host ipfs add --recursive /export/augur-ui
```
Then navigate to http://localhost:1234/ipfs/Qmf8Zu32FaVxH9CGWxXSP771nXvY7vQ4AAWZnnmp4WSzfv/#/categories?augur_node=wss%3a%2f%2faugur-node.augur.casino&ethereum_node_http=https%3a%2f%2fmainnet.infura.io

Notice in the console that 127.0.0.1:9001 is being used for `augur-node` rather than the augur-node supplied in the query string.

**Comment by sharkcrayon** [comment]
Adding to issue tracker: https://app.clubhouse.io/augur/story/15104/github-ipfs-hosting-workflow-is-broken
