### ISSUE TITLE
Vulnerabilities found by npm audit

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur-ui#2293]
npm audit results: https://gist.github.com/tinybike/f5ed98cc0cef1d34b736efe756376fbd

**Comment by adrake33** [comment]
https://app.clubhouse.io/augur/story/16662/github-fix-vulnerabilities-found-by-npm-audit

**Comment by adrake33** [comment]
Closing this, as Pete and Justin are working on using Greenkeeper to give us security updates on a continuous basis.
