### ISSUE TITLE
Suggestion: resolved markets should show resolution timestamp

### ISSUE THREAD

**Issue by veox** [AugurProject/augur-ui#2358]
I'd like to create a new market `Mnew` on whether an existing market `Mdisp` will resolve (be finalised) by date `D`.

Since this info is not displayed in the UI, it would be hard for future reporters on market `Mnew` to make a determination whether `Mdisp` indeed closed before `D` or after.

A work-around is possible, using the `augur.markets.getMarketsInfo(...)` API call for a specific market, then checking `reportingState` and `finalizationTime`.

However, this is best IMO integrated into the UI, rather than provided by a third-party tool.

-----

EDIT: Is this better suited for `AugurProject/augur-app`?.. I can "move" it there.

**Comment by adrake33** [comment]
Issue moved to [AugurProject/augur #308](https://github.com/AugurProject/augur/issues/308) via [**ZenHub**](https://www.zenhub.com/)
