### ISSUE TITLE
Bug: Cannot favorite markets in the dispute list

### ISSUE THREAD

**Issue by jfarid27** [AugurProject/augur-ui#2482]
Currently cannot favorite markets in `/reporting-dispute-markets` on 1.7.1.

**Comment by adrake33** [comment]
This has been added to our internal tracking system: https://app.clubhouse.io/augur/story/18090/markets-cannot-be-added-to-favorites

**Comment by adrake33** [comment]
Closing, since this was fixed in v1.8.0
