### ISSUE TITLE
Order Book calculates estimate cost using incorrect number of shares

### ISSUE THREAD

**Issue by epheph** [AugurProject/augur-ui#2498]
This is easiest to replicate using the dev seed data from a pop-geth.

When looking at any market (even yesNo), with an account that is NOT the main 0x913 account (since taking own orders is a different code path), do this:

- Sell into the best green buy order. you should now have 0.001 no.
- Click on the best red ask order but don't take it. Those estimated values make sense. You satisfy that order with the "no" share you previously purchased and no eth
- Click on the next best red ask order but don't take it. Those estimated values are wrong because the UI is estimating it as if you had 0.002 shares. Because it thinks you have this much, it doesn't forward enough ETH in the transaction.
- Same thing with the worst red ask order, it assumes you have 0.003 when you click on it, but your quantity of available shares to sell doesn't increase just because you click on different order, the number should have been 0.001 no matter which you clicked on.

**Comment by bthaile** [comment]
Issue is in `augur.js/src/trading/simulation/simulate-fill-ask-order.js` 

it loops through orders in the book that are going to be taken `  matchingSortedAsks.forEach(function (matchingAsk) ` and adds users share tokens to `takerSharesDepleted` on each loop. So the user has 0.001 token shares which gets added twice. In this example.

Need to only add user's share tokens once even though multiple orders are going to be taken.

**Comment by bthaile** [comment]
https://github.com/AugurProject/augur.js/pull/557
