### ISSUE TITLE
setState warning on unmounted component

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur-ui#2499]
![image](https://user-images.githubusercontent.com/6775839/49175717-10aa2080-f2fe-11e8-8ee6-b05cca7bf2a2.png)

a warning is being shown for FilterSearch component

**Comment by adrake33** [comment]
Issue moved to [AugurProject/augur #252](https://github.com/AugurProject/augur/issues/252) via [**ZenHub**](https://www.zenhub.com/)
