### ISSUE TITLE
markets in designated_reporting have full timer on them in market list

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur-ui#2502]
These show up for non-designated reporter account

<img width="1567" alt="screen shot 2018-11-28 at 1 46 28 pm" src="https://user-images.githubusercontent.com/6775839/49184382-0e52c100-f314-11e8-8f85-06cdf1c1235e.png">

this ended up going away and can't repro since dev.augur.net was updated

**Comment by bthaile** [comment]
Are the market DR end time same as block time? It needs to be 1 second past.

**Comment by phoebemirman** [comment]
this looks normal for me now

<img width="1383" alt="screen shot 2018-11-28 at 5 05 09 pm" src="https://user-images.githubusercontent.com/6775839/49192423-cf326900-f32f-11e8-849b-c3ce5907e440.png">

**Comment by bthaile** [comment]
There was a commit to masyer that caused dev.augur.net to updated. I noticed when I hard refreshed and the issue mentioned above was gone.

**Comment by adrake33** [comment]
Issue moved to [AugurProject/augur #253](https://github.com/AugurProject/augur/issues/253) via [**ZenHub**](https://www.zenhub.com/)
