### ISSUE TITLE
Need design input on filter drop downs

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/augur-ui#2503]
How should we handle filter dropdowns on mobile?
<img width="428" alt="image" src="https://user-images.githubusercontent.com/328965/49186177-b79bb600-f318-11e8-998c-98f4bf10f147.png">

**Comment by adrake33** [comment]
Yeah, let's just remove the "Markets with" for desktop & mobile. And instead of "All Markets" as an option, let's change it to "All Fees".
