### ISSUE TITLE
Migrate Performance chart on Portfolio page to D3

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur-ui#2511]
(Copying from CH.)

Joey requested that we add timestamps to the chart when hovering. This should be done across all of the charts. John said this should be pretty straightforward to do in D3.

**Comment by JohnDanz** [comment]
https://github.com/AugurProject/augur-ui/pull/2500

**Comment by adrake33** [comment]
Issue moved to [AugurProject/augur #307](https://github.com/AugurProject/augur/issues/307) via [**ZenHub**](https://www.zenhub.com/)
