### ISSUE TITLE
Feature Request: Better page navigation in Portfolio

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur-ui#2566]
The user BPike9485 on Discord requested a better way to click through pages on the Portfolio:Positions page. Currently, if he wants to go to the fifth page, he has to click through the first 4 pages to get there, so he'd like a quicker UI for doing this.

**Comment by bthaile** [comment]
Better way to have condensed position cards so 50 can be shown. Also a way for fitering and sorting like the market list view.so the user can choose which positions to see.

**Comment by joeykrug** [comment]
sorting is there now, no longer paginated
