### ISSUE TITLE
Feature Request: Better way to reach reporting/dispute view from markets and portfolio

### ISSUE THREAD

**Issue by SebastianMetzger** [AugurProject/augur-ui#2586]
For me it is not intuitive in the moment to check on the current reporting state of a market when browsing markets or when looking at my portfolio.
You should be able to jump there directly as the markets in my portfolio a probably the once I am most interested about in reporting as well.

**Comment by Chwy5** [comment]
This will be addressed in the portfolio pg redesign

**Comment by adrake33** [comment]
Closing since this will be addressed by the redesign.
