### ISSUE TITLE
If a transaction fails - it stays in pending state (doesn't seem to be updating) 

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur-ui#2770]
notifications status is incorrect when transaction fails. 
- need to update notification status when transaction fails. 

more specifically when a pending order fails, need to:

Currently the "pending order" inline label sticks around even after the transaction fails:

@Chwy5  What should the UI show to the user in the `open orders` when a pending order fails?

**Comment by Chwy5** [comment]
I think it should Show "Failed"

**Comment by bthaile** [comment]
Seems the row should be dismissable. That way it sticks around to tell the user it failed. 

Of course the bell alert should say failed.

**Comment by bthaile** [comment]
@Chwy5 what should we do with the open order row in portfolio and market trading page when the tx fails?

**Comment by Chwy5** [comment]
For Now, if a transaction fails:

The pending transaction in Open Orders (for both the trading pg and portfolio pg) should disappear.
The message in the bell (the toast message should change from pending to Failed)

**Comment by pgebheim** [comment]
@bthaile Adding this to the Trading Page work for 2.0b because its a case we wanna consider with the new infrastructure.

Can be moved if its not needed.

**Comment by pgebheim** [comment]
Closing, new transaction work happening zeroX
