### ISSUE TITLE
portfolio: Filled order quad text sizing

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur-ui#2773]
existing tix for numeric values for portfolio.

Also whole table row in filled orders needs to be 11px.

Market title needs to be 12px.

**Comment by Chwy5** [comment]
@matt-bullock please review and close if this looks correct

**Comment by matt-bullock** [comment]
outcome should be medium in weight (500)

**Comment by bthaile** [comment]
@phoebemirman comment on this issue.

**Comment by Chwy5** [comment]
@matt-bullock double check this is correct and close if it is

**Comment by matt-bullock** [comment]
closing
