### ISSUE TITLE
filled orders table is blank but i do have a filled order

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur-ui#2781]
<img width="1551" alt="Screen Shot 2019-03-19 at 2 39 43 PM" src="https://user-images.githubusercontent.com/6775839/54643736-dd2e0600-4a54-11e9-87e3-22eaca68ca0d.png">
<img width="1404" alt="Screen Shot 2019-03-19 at 2 39 32 PM" src="https://user-images.githubusercontent.com/6775839/54643737-ddc69c80-4a54-11e9-94a9-219773a262c8.png">

i was the filler. it showed up eventually, so probably a loading issue

**Comment by bthaile** [comment]
I think this has been addressed with recent optimizations. Moving to `design review` for testing

@Chwy5 can you confirm that filled orders do show up in portfolio and you haven't see a big lag specifically with filled orders.

**Comment by Chwy5** [comment]
worked for me - closing
