### ISSUE TITLE
Notifications: unsigned orders didn't trigger notification

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur-ui#2786]
note from Chwy:

unsigned orders https://github.com/AugurProject/augur/issues/1246 I didnt get this notification...I triggered an orphaned order(here is tx hash for it) 0xfe93c22d73432a4f0425806eb4e67505bf1d62a19e63ac05d132376bd8506d35....didnt get notifiaction in Notifiaction section

**Comment by andrewdamelio** [comment]
@bthaile @Chwy5 

This notification is for unsigned initial market creation orders, not orphaned order. 
(We don't have a notification for this. FYI)

To trigger this notification...
- create a new market with some initial liquidity. 
- Accept the first TX to create the market
- Refresh/Close your browser when the next liquidity TX's appear.

 
You should now be notified of these pending unsigned orders.

**Comment by Chwy5** [comment]
Followed those steps and still not getting a message in my Notifications....If I go to portfolio under my created I can click on the market and go there and see that it has no orders on the book

**Comment by bthaile** [comment]
@andrewdamelio I tested the unsigned orders notification on new-trading-page-layout branch and got a notification for unsigned orders but the active view button didnt bring up the modal. Can you verify?

**Comment by Chwy5** [comment]
Also...I did get the notification on one test, but it did not show up on the top of my Notifications list ...showed up 3rd from the bottom of 24 notifications

**Comment by andrewdamelio** [comment]
Correct,  as mentioned only three of the notification are wired up to modals. (Claim Proceeds, Finalize market and Sell Complete Sets)

Taking another look at the codebase I believe there is a modal I can use for this ```modal-sign-transaction.ts```

**Comment by andrewdamelio** [comment]
@bthaile Doesn't appear like there are any modal available at this time to accommodate this.

**Comment by andrewdamelio** [comment]
@Chwy5 @bthaile can we close this ticket?

I confirmed early this week that the Unsigned Orders Notifications and Modal are working correctly on localhost / Rinkeby.

**Comment by Chwy5** [comment]
i'll push to 1.16 and confirm after m-repo release
