### ISSUE TITLE
notifications: dr didn't get count down timer

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur-ui#2787]
notes from chwy

designated report with count down timer #1121 - I didnt get this notification. I created a market in Acct 1 and made Acct 2 the designated reporter...never got notification in acct 2 or countdown clock

**Comment by andrewdamelio** [comment]
@bthaile @Chwy5 

I just tested this again, with the same test case as listed above -- it worked.
![image](https://user-images.githubusercontent.com/1683736/54704436-188e0a80-4b11-11e9-88e6-3f88e42f77d3.png)

---
To help confirm this is working, add the market that is being reported on to your favorites as the DR acount.

If you see the DR message/countdown in the favorite list but you don't see the notification there is a problem with the notification. 

![image](https://user-images.githubusercontent.com/1683736/54704633-81758280-4b11-11e9-9238-5b734901d491.png)

**Comment by Chwy5** [comment]
I just tested this again and I am still not getting the Notification for designated reporter

**Comment by Chwy5** [comment]
OK this is actually working....I was creating markets expiring tomorrow....but b/c of the 3 day wait period....I dont get the dr notification until the 3 day period gets triggered.....Closing this ticket
