### ISSUE TITLE
notifications: market maker claim validity bond and no-show bond

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur-ui#2788]
notes from chwy

market maker can claim validity bond (ETH) and no-show bond (REP) from mailbox #1244 _ i Have not got this

**Comment by andrewdamelio** [comment]
@Chwy5 For this card "Claim Available Stake And Reporting Fees". 
For the case where it doesn't show up, can you please confirm you have fees to collect via the My Reporting page?

An easy way to tell if you **SHOULD** see this notification is just to goto **Portfolio / My Reporting** and if you have any REP/ETH to claim here, you should see the notification. 

![image](https://user-images.githubusercontent.com/1683736/54705484-4d02c600-4b13-11e9-94d4-de653d780dbb.png)

**Comment by Chwy5** [comment]
![3-21claim](https://user-images.githubusercontent.com/41301809/54769767-4b4f0600-4bd8-11e9-882d-6cf4623131a3.jpg)

**Comment by Chwy5** [comment]
The numbers in my notification match as well.. but when i click on view in the notification nothing happens

**Comment by bthaile** [comment]
@andrewdamelio there are notifications not wired up. At least the modal would not come up and no console errors. See if you can get this modal to come up. 

I’ll pull over the other tix or create them for the other notifications that have active view buttons but no modal comes up.

**Comment by andrewdamelio** [comment]
@bthaile Sounds good.

For this, should i use the same modal we use on the My Reporting page?
![image](https://user-images.githubusercontent.com/1683736/54830194-6f6d1e80-4c8e-11e9-9f9e-bd58a07caff0.png)

**Comment by andrewdamelio** [comment]
@Chwy5 @bthaile can we close this ticket?

This modal has been updated.

**Comment by Chwy5** [comment]
Moving it to post MR will check after we switch
