### ISSUE TITLE
Feature request: filter markets by remaining time till expiration

### ISSUE THREAD

**Issue by morninglite** [AugurProject/augur-ui#2973]
The default view (sorted by open interest, fees <5%) is full of markets that expire more than a year from now. One expires in 2060. It would be very convenient to be able to filter these out, while still keeping the open interest sort order (or sorting by volume, for that matter).

Since the UI already prevents users from creating new markets running longer than 6 months, it stands to reason that we should be able to hide the existing ones from the list. In fact, since new users might not understand the risks of betting on long-running markets in Augur v1, it might even be best to filter them out by default, just like fees > 5% are done already.

It would be nice to also be able to choose an even shorter timeframe, for example 1 month. If someone only wants to lock up ETH for a short period, we should make it easy for them, rather than let them get frustrated and not engage at all. 

That's secondary to the 6-month filter, though, which seems like it should maybe be a priority.

**Comment by pgebheim** [comment]
This has been handled in the new sort designs for v2 market lists.
