### ISSUE TITLE
augur-node: add spread filter

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur-ui#3028]
update augur-node getMarkets endpoint `/src/server/getters/get-markets.ts` to take a new filter for spread.

see https://github.com/AugurProject/augur/issues/1782

for details on algo

**Comment by pgebheim** [comment]
@ryanberckmans -- This needs to go into `in progress` yes?

**Comment by pgebheim** [comment]
Making a sister ticket here to do this in V2.
